/*
SQLyog Community v12.2.1 (64 bit)
MySQL - 5.5.46-0+deb8u1 : Database - distributor_kokola
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`distributor_kokola` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `distributor_kokola`;

/*Table structure for table `kj` */

DROP TABLE IF EXISTS `kj`;

CREATE TABLE `kj` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `TGL` datetime DEFAULT NULL,
  `TRIWULAN` varchar(100) DEFAULT NULL,
  `BULAN_INPUT` varchar(100) DEFAULT NULL,
  `NAMA_DIST` varchar(100) DEFAULT NULL,
  `DAERAH` varchar(100) DEFAULT NULL,
  `ID_PRODUK` varchar(25) DEFAULT NULL,
  `NAMA_PRODUK` varchar(200) DEFAULT NULL,
  `ITEM_CODE` varchar(100) DEFAULT NULL,
  `HARGA` int(11) DEFAULT NULL,
  `BLN_AKHIR` int(11) DEFAULT NULL,
  `FORECAST` int(11) DEFAULT NULL,
  `PERSEN` varchar(20) DEFAULT NULL,
  `BULAN1` varchar(100) DEFAULT NULL,
  `BULAN2` varchar(100) DEFAULT NULL,
  `BULAN3` varchar(100) DEFAULT NULL,
  `TOTAL_VALUE` double DEFAULT NULL,
  `SET_BLN1` varchar(100) DEFAULT NULL,
  `SET_BLN2` varchar(100) DEFAULT NULL,
  `SET_BLN3` varchar(100) DEFAULT NULL,
  `ACCOUNT_ID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`ACCOUNT_ID`),
  KEY `ACCOUNT_ID` (`ACCOUNT_ID`),
  KEY `ITEM_CODE` (`ITEM_CODE`)
) ENGINE=MyISAM AUTO_INCREMENT=6882 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
/*!50100 PARTITION BY HASH (ACCOUNT_ID)
PARTITIONS 30 */;

/*Table structure for table `order_confirm` */

DROP TABLE IF EXISTS `order_confirm`;

CREATE TABLE `order_confirm` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ORDER` varchar(100) DEFAULT NULL,
  `ID_CONFIRM` varchar(100) DEFAULT NULL,
  `TGL_ORDER` datetime DEFAULT NULL,
  `ACCOUNT_ID` int(11) NOT NULL DEFAULT '0',
  `ID_PRODUK` varchar(50) DEFAULT NULL,
  `ITEM_CODE` varchar(255) NOT NULL DEFAULT '',
  `JML_ORDER` int(10) DEFAULT NULL,
  `KUBIKASI` double(4,3) DEFAULT NULL,
  `TGL_CONFIRM` datetime DEFAULT NULL,
  `FLAG` varchar(1) DEFAULT '0',
  `FLAG2` varchar(1) DEFAULT NULL,
  `CATATAN2` text,
  `SBG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Id`,`ACCOUNT_ID`,`ITEM_CODE`),
  KEY `ID_ORDER` (`ID_ORDER`),
  KEY `ID_PRODUK` (`ID_PRODUK`)
) ENGINE=InnoDB AUTO_INCREMENT=9673 DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED
/*!50100 PARTITION BY HASH (ACCOUNT_ID)
PARTITIONS 40 */;

/*Table structure for table `order_distributor` */

DROP TABLE IF EXISTS `order_distributor`;

CREATE TABLE `order_distributor` (
  `ID_ORDER` varchar(15) NOT NULL DEFAULT '',
  `TGL` datetime DEFAULT NULL,
  `USERID` varchar(20) DEFAULT NULL,
  `CATATAN` varchar(255) DEFAULT NULL,
  `ACCOUNT_ID` varchar(25) DEFAULT NULL,
  `FLAG` varchar(1) DEFAULT '1',
  `CATATAN2` text,
  `SBG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_ORDER`),
  UNIQUE KEY `ID_ORDER_UNIQUE` (`ID_ORDER`),
  KEY `ID_ORDER` (`ID_ORDER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
